from typing import Protocol


class PlaybackPort(Protocol):
    def play(self, context: str = "vlc_play", **fields: object) -> bool: ...
    def pause(self, context: str = "vlc_pause", **fields: object) -> bool: ...
    def stop(self, context: str = "vlc_stop", **fields: object) -> bool: ...
    def set_time(self, value: int, context: str = "vlc_set_time", **fields: object) -> bool: ...
    def set_rate(self, value: float, context: str = "vlc_set_rate", **fields: object) -> bool: ...
    def audio_set_volume(self, value: int, context: str = "vlc_audio_set_volume") -> bool: ...
    def audio_toggle_mute(self, context: str = "vlc_audio_toggle_mute") -> bool: ...


class PlaybackController:
    def __init__(self, player: PlaybackPort):
        self.player = player
